<a href="https://colab.research.google.com/github/pazylkhann/d2l.ai-learning-process/blob/main/Preliminaries/Data%20Manipulation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Getting Started

In [2]:
import torch

In [3]:
x = torch.arange(4, 12, 2, dtype=torch.float32)
x

tensor([ 4.,  6.,  8., 10.])

In [4]:
x.numel()

4

In [5]:
x.shape

torch.Size([4])

In [6]:
X = x.reshape(2, 2)
X

tensor([[ 4.,  6.],
        [ 8., 10.]])

In [7]:
xx = x.reshape(2, -1)    # We can put -1 if we already know that w = n/h, so it automatically finds other variable
xx

tensor([[ 4.,  6.],
        [ 8., 10.]])

In [8]:
torch.zeros((2, 3, 4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [9]:
torch.ones((2, 3, 4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [10]:
torch.randn(3, 4)    # filled by standard Gaussian(normal) distribution with mean 0 and standard deviation 1

tensor([[ 0.3184, -0.8533,  1.5597, -1.7033],
        [ 0.5809, -1.0222, -1.1704, -0.5552],
        [-0.2780, -1.0679,  2.2107,  0.8727]])

In [ ]:
torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

##Indexing and Slicing

In [12]:
X = torch.arange(12, dtype=torch.float32)
X = X.reshape(3, 4)
X[-1], X[1:3]

(tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

In [15]:
X[1, 2] = 17  # also we can write elements of matrix by specifying indices
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5., 17.,  7.],
        [ 8.,  9., 10., 11.]])

In [16]:
X[:2, :] = 12
X

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

##Operations

In [17]:
x = torch.arange(12, dtype=torch.float32)
torch.exp(x)

tensor([1.0000e+00, 2.7183e+00, 7.3891e+00, 2.0086e+01, 5.4598e+01, 1.4841e+02,
        4.0343e+02, 1.0966e+03, 2.9810e+03, 8.1031e+03, 2.2026e+04, 5.9874e+04])

In [18]:
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
x + y, x - y, x*y, x/y, x**y

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

In [23]:
X = torch.arange(12, dtype=torch.float32).reshape(3, 4)
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
torch.cat((X, Y), dim=0), torch.cat((X, Y), dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [39]:
X < Y, X > Y, X == Y

(tensor([[False, False, False, False],
         [False, False, False, False],
         [False, False, False, False]]),
 tensor([[False,  True,  True,  True],
         [ True,  True,  True,  True],
         [ True,  True,  True,  True]]),
 tensor([[ True, False, False, False],
         [False, False, False, False],
         [False, False, False, False]]))

In [26]:
X.sum()

tensor(66.)

##Broadcasting

In [40]:
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [29]:
a + b   # replicating matrix a along the columns and matrix b along the rows

tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [43]:
c = torch.arange(1, 13).reshape((2, 2, 3))
d = torch.tensor([
    [1, 2, 3], [4, 1, 2]
])
c + d

tensor([[[ 2,  4,  6],
         [ 8,  6,  8]],

        [[ 8, 10, 12],
         [14, 12, 14]]])

##Saving Memory

In [31]:
before = id(Y)
Y = Y + X
id(Y) == before           # Proving that after we get new allocated memory and and then point variable to new allocated memory

False

In [32]:
Z = torch.zeros_like(Y)        # performing in-place operation
print("id(Z):", id(Z))
Z[:] = X + Y
print("id(z)", id(Z))
# We can assign the result of an operation to a previously allocated array Y by using slice notation: Y[:] = <expression>.
# To illustrate this concept, we overwrite the values of tensor Z, after initializing it, using zeros_like, to have the same shape as Y.

id(Z): 139291977077920
id(z) 139291977077920


In [33]:
before = id(X)
X += Y       # reducing memory overhead of the operation if there is no subsequent computations
id(X) == before

True

## Conversion to other Python Objects

In [35]:
A = X.numpy()
B = torch.from_numpy(A)
type(A), type(B)
#  The torch tensor and NumPy array will share their underlying memory, and
# Changing one through an in-place operation will also change the other.

(numpy.ndarray, torch.Tensor)

In [37]:
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)

##Summmary
The tensor class is the main interface for storing and manipulating data in deep learning libraries. Tensors provide a variety of functionalities including construction routines; indexing and slicing; basic mathematics operations; broadcasting; memory-efficient assignment; and conversion to and from other Python objects.