<a href="https://colab.research.google.com/github/pazylkhann/d2l.ai-learning-process/blob/main/Preliminaries/Linear_Algebra_in_AI_ML(basics).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Linear Algebra

In [1]:
import torch

##Scalars

In [2]:
x = torch.tensor(3.0)
y = torch.tensor(2.0)
x + y, x-y, x*y, x/y, x**y

(tensor(5.), tensor(1.), tensor(6.), tensor(1.5000), tensor(9.))

##Vectors

In [3]:
x = torch.arange(3)
x

tensor([0, 1, 2])

In [4]:
x[2]

tensor(2)

In [5]:
len(x)

3

In [6]:
x.shape         ##  we use order to number of axes, also dimensioality to the number of components

torch.Size([3])

##Matrices

In [7]:
A = torch.arange(6).reshape(3, 2)
A

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In [8]:
A.T        # transpose of the matrix

tensor([[0, 2, 4],
        [1, 3, 5]])

In [9]:
A = torch.tensor([[1, 2, 3], [2, 0, 4], [3, 4, 5]])          #  Symmetric matrix is when A = A.T
A == A.T

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])


##Tensors

In [10]:
A = torch.arange(24).reshape(2, 3, 4)     # tensors can work with higher-order(dimension)
A

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

##Basic Properties of tensor arithmetic

In [11]:
A = torch.arange(6, dtype=torch.float32).reshape(2, 3)
B = A.clone() # Assign a copy of A to B by allocating new memory
A, A + B

(tensor([[0., 1., 2.],
         [3., 4., 5.]]),
 tensor([[ 0.,  2.,  4.],
         [ 6.,  8., 10.]]))

In [12]:
A * B  # Hadamard product = elementwise product of two matrices

tensor([[ 0.,  1.,  4.],
        [ 9., 16., 25.]])

In [34]:
a = 2
X = torch.arange(24).reshape(2, 3, 4)
a + X, (a * X).shape, len(X)

(tensor([[[ 2,  3,  4,  5],
          [ 6,  7,  8,  9],
          [10, 11, 12, 13]],
 
         [[14, 15, 16, 17],
          [18, 19, 20, 21],
          [22, 23, 24, 25]]]),
 torch.Size([2, 3, 4]),
 2)

##Reduction

In [14]:
x = torch.arange(3, dtype=torch.float32)
x, x.sum()

(tensor([0., 1., 2.]), tensor(3.))

In [15]:
A.shape, A.sum()     # sums over the elements of tensors of arbitrary shape

(torch.Size([2, 3]), tensor(15.))

In [16]:
A.shape, A.sum(axis=0).shape  # specify the axes along which the tensor should be reduced

(torch.Size([2, 3]), torch.Size([3]))

In [17]:
A.shape, A.sum(axis=1).shape

(torch.Size([2, 3]), torch.Size([2]))

In [18]:
A.sum(axis=[0, 1]) == A.sum()   # Same as A.sum()

tensor(True)

In [19]:
A.mean(), A.sum() / A.numel()

(tensor(2.5000), tensor(2.5000))

In [20]:
A.mean(axis=0), A.sum(axis=0) / A.shape[0]

(tensor([1.5000, 2.5000, 3.5000]), tensor([1.5000, 2.5000, 3.5000]))

##Non-Reduction Sum

In [21]:
sum_A = A.sum(axis=1, keepdims=True)   # keep the number of axes unchanged
sum_A, sum_A.shape

(tensor([[ 3.],
         [12.]]),
 torch.Size([2, 1]))

In [22]:
A / sum_A

tensor([[0.0000, 0.3333, 0.6667],
        [0.2500, 0.3333, 0.4167]])

In [23]:
  A.cumsum(axis=0)  # the cumulative some of elements of A along some axis

tensor([[0., 1., 2.],
        [3., 5., 7.]])

##Dot Products

In [24]:
y = torch.ones(3, dtype=torch.float32) # The dot product of two vectors is a sum over the products of the elements at the same position
x, y, torch.dot(x, y)

(tensor([0., 1., 2.]), tensor([1., 1., 1.]), tensor(3.))

In [25]:
torch.sum(x * y)  # equivalent way of finding dot product

tensor(3.)

## Matrix -- Vector products

In [26]:
A.shape, x.shape, torch.mv(A, x), A@x      # m*n matrix and n-dimensional vector product

(torch.Size([2, 3]), torch.Size([3]), tensor([ 5., 14.]), tensor([ 5., 14.]))

## Matrix -- Matrix multiplication

In [28]:
B = torch.ones(3, 4)          # A(m*k), B(k*n), so basically while multiplying both, we multiply row vectors of A and column vectors of B
torch.mm(A, B), A@B

(tensor([[ 3.,  3.,  3.,  3.],
         [12., 12., 12., 12.]]),
 tensor([[ 3.,  3.,  3.,  3.],
         [12., 12., 12., 12.]]))

##Norms

In [29]:
u = torch.tensor([3.0, -4.0])      # l2 norm(Euclidean norm) where we get root of the sum of squared elements
torch.norm(u)

tensor(5.)

In [31]:
torch.abs(u).sum()     # l1 norm(Manhattan distance) where it sums the absolute values of vector's elements

tensor(7.)

In [32]:
torch.norm(torch.ones((4, 9)))    # For Matrices Frobenius norm is used to calculate root of the sum of the all elemnts of the matrix

tensor(6.)

## Exercises

In [36]:
len(X[0])      # basically len(X) defines first dimension's length of the matrix or tensor

3

In [40]:
A / A.sum(axis=1, keepdims=True)

tensor([[0.0000, 0.3333, 0.6667],
        [0.2500, 0.3333, 0.4167]])

In [43]:
X.sum(axis=2).shape      # (2, 3, 4) vector's shapes based on axis

torch.Size([2, 3])

In [46]:
torch.norm(X.float())

tensor(65.7571)

In [50]:
import numpy as np
A = torch.ones(100, 200)
B = torch.ones(100, 200)
C = torch.ones(100, 200)
tensor = np.stack([A, B, C], axis=2)
B_recovered = tensor[:, :, 1]
B_recovered

array([[1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       ...,
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.]], dtype=float32)